#!/bin/sh
### BEGIN INIT INFO
# Provides:          gowebapp
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       gowebapp service
### END INIT INFO

NAME=gowebapp
GOPATH=/home/vagrant/src/github.com/josephspurrier/$NAME
SCRIPT=$GOPATH/$NAME
RUNAS=vagrant

PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log


start() {
  if [ -f /var/run/$PIDFILE ] && kill -0 $(cat /var/run/$PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  cd $GOPATH
  echo 'Starting service…' >&2
  su $RUNAS -c "$SCRIPT > $LOGFILE 2>&1 &"
  PID=`ps -fu $RUNAS| grep "$NAME" | grep -v "grep" | awk '{print $2}'`
          if [ -z $PID ]; then
            printf "%s\n" "Service failed to start."
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Service started!"
        fi
}

stop() {
  if [ ! -f "$PIDFILE" ] || [ ! -s "$PIDFILE" ]; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  killall $NAME && echo "" > $PIDFILE
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
